"""Research universe: liquid NSE large caps (approx. Nifty 50 + Nifty Next 50, as known in 2025).

SURVIVORSHIP WARNING: this is a *current* constituent list. Stocks that fell out of the
indices (or were delisted) over 2010-2026 are absent, so absolute long-only returns are
biased upward. Compare strategies *relative to buy-and-hold of the same universe*.
Tickers that fail to download (renames/demergers) are skipped and reported.
"""

NIFTY50 = """RELIANCE TCS HDFCBANK ICICIBANK INFY BHARTIARTL ITC SBIN LT KOTAKBANK HINDUNILVR AXISBANK
BAJFINANCE MARUTI SUNPHARMA M&M NTPC TITAN ULTRACEMCO ASIANPAINT POWERGRID TATASTEEL ONGC COALINDIA
ADANIENT ADANIPORTS BAJAJFINSV JSWSTEEL NESTLEIND WIPRO HCLTECH TECHM GRASIM HINDALCO CIPLA DRREDDY
EICHERMOT BRITANNIA APOLLOHOSP BPCL HEROMOTOCO INDUSINDBK SBILIFE HDFCLIFE TATACONSUM DIVISLAB
BAJAJ-AUTO SHRIRAMFIN TRENT""".split()

NEXT50 = """AMBUJACEM BANKBARODA BERGEPAINT BOSCHLTD CANBK CHOLAFIN COLPAL DABUR DLF GAIL GODREJCP HAVELLS
ICICIGI ICICIPRULI INDIGO IOC IRCTC JINDALSTEL LODHA MARICO MUTHOOTFIN NAUKRI PIDILITIND PNB PFC
RECLTD SHREECEM SIEMENS SRF TORNTPHARM TVSMOTOR UNITDSPR VEDL ZYDUSLIFE ABB BEL HAL POLYCAB
PERSISTENT LUPIN AUROPHARMA BIOCON TATAPOWER PAGEIND MRF COFORGE MPHASIS ASHOKLEY CUMMINSIND
GODREJPROP VOLTAS ADANIPOWER BAJAJHLDNG""".split()

SYMBOLS = NIFTY50 + NEXT50
BENCHMARKS = {"NIFTY50_PRICE": "^NSEI"}


def yahoo(sym: str) -> str:
    return sym if sym.startswith("^") or "." in sym.split("&")[-1] and sym.endswith(".NS") else f"{sym}.NS"
